### ISSUE TITLE
How to deploy kubevirt-gpu-device-plugin on OKD Cluster?

### ISSUE THREAD

**Issue by rupang790** [NVIDIA/kubevirt-gpu-device-plugin#11]
I tried to deploy kubevirt-gpu-device-plugin on OKD cluster.
In my cluster, I already deploy kubevirt-hyperconverged/NFD/GPU-operator plugins and I check GPU-operator is working well on the Pods. After that I would like to test the gpu on Kubevirt vm but it seems to install Kubevirt-gpu-device-plugin for Kubevirt vm with GPU.
I cloned it and tried to deploy on my cluster, but It shows below error after "make" command.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/40801176/99468317-a1fb7d00-2983-11eb-8842-1bdfa014a20f.png">

Do you have any idea about this?

**Comment by rthallisey** [comment]
Could be how you setup your GOROOT.  Running `make` from the master branch worked fine for me.
