### ISSUE TITLE
Assigning a Single Physical GPU to Multiple VMs in KubeVirt

### ISSUE THREAD

**Issue by tunahanertekin** [NVIDIA/kubevirt-gpu-device-plugin#115]
Hi there,

I’m trying to assign a single physical GPU to multiple VMs.

Based on my research, GPU passthrough and vGPU software are the only methods available for enabling GPU acceleration in KubeVirt VMs. Since GPU passthrough doesn’t allow me to assign the same GPU to multiple VMs, vGPU seems to be my only option.

Are there any alternatives to vGPU that would allow me to achieve this? Is there another way to enable GPU usage across multiple VMs while maintaining a one-to-many relationship between a physical GPU and VMs?

Thanks in advance!

**Comment by rthallisey** [comment]
vGPUs were designed specifically for sharing the entire GPU with multiple vms.  I'm not aware of an alternative.

If you don't need to share the entire GPU, you can use Multi-Instance GPU (MIG) mode - https://www.nvidia.com/en-us/technologies/multi-instance-gpu/.  That will provide hardware separation which can be partitions to multiple vms.
