### ISSUE TITLE
Feature request: Live migration of VMIs that use GPUs

### ISSUE THREAD

**Issue by haslersn** [NVIDIA/kubevirt-gpu-device-plugin#15]
Is it possible to live migrate VMIs that use GPUs?

**Comment by rthallisey** [comment]
Under the hood, kvm requires that you unplug all non-usb devices before migration.  So you'll need to unplug those device while the VMI is up.  Iirc, kubernetes doesn't support hot plug/hot unplug of devices from pods just yet.  However, kubevirt can unplug from the VM using the virt-launcher pod and that's something being worked in the community.  Keep an eye out for some upcoming work on snapshots as it's relevant to what your asking.

Short answer is: no, but there's work in progress.

**Comment by haslersn** [comment]
Is it already supported by kubevirt-gpu-device-plugin, or is work both in the plugin and in KubeVirt required?

**Comment by rthallisey** [comment]
The kubevirt-gpu-device-plugin is for exposing gpus on a node, so it already does what's necessary to enable migration.  Issue should be on KubeVirt.

**Comment by rthallisey** [comment]
This might be of interest https://github.com/kubevirt/community/pull/73
