### ISSUE TITLE
Is it available to use kubevirt-gpu-device-plugin with gpu-operator on OKD Cluster?

### ISSUE THREAD

**Issue by rupang790** [NVIDIA/kubevirt-gpu-device-plugin#16]
Currently, I use OKD cluster version 4.5 with some plugins such as Kubevirt.
And I would like to use GPU for Kubevirt vm but I could not attach it with GPU-Operator.
So I consider to use kubevirt-gpu-device-plugin for vm now.
Is it available to use kubevirt-gpu-device-plugin with gpu-operator? 
Do someone try to use them together on OKD or OCP cluster as well?

**Comment by rthallisey** [comment]
I haven't tried using them together, but you might get an error thrown during plugin registration or device Allocation.  The gpu-operator and device-plugin satisfy the same interface by returning a list of devices for Kubernetes to advertise on a node and they both respond to Allocate.  The GPU-operator will likely fail on the Allocate request that kubevirt-gpu-device-plugin succeeds on and vice versa.  At that point, listing the devices by both plugins could stabilize the available and allocated gpus.  So it's possible... worth a try at least.   I would be interested in hearing the results.

**Comment by rupang790** [comment]
@rthallisey, Hi I am back with results of my test.
According to https://github.com/kubevirt/hyperconverged-cluster-operator/issues/1290#issue-870718003, I have problem to use it on OKD cluster. Please check  below:

Nvidia GPU is not recognized on OKD 4.5 cluster (Kubevirt-hyperconverged 1.4.0-unstable version).
Before I issued about kubevirt with gpu which is tested on Kubernetes and 1.4.0-unstable operator is updated. 
https://github.com/kubevirt/hyperconverged-cluster-operator/issues/1227#issue-851036553

However, I tried to install kubevirt-gpu-dp on OKD 4.5 cluster with same way that I tested on Kubernetes, It seems not recognize the GPU device. (configure kernel command and VFIO-PCI)
I am not sure it is the issue with kubevirt, nivida or Kubernetes kubelet, so I would like to share and request this issue with all of you.

** ```Nvidia.com/gpu``` from results of command as below is recognized by ```gpu-operator```. And also it was work with gpu-operator as well.
>. From Worker
```
[core@worker01 ~]$ sudo lspci -nnk -d 10de:
86:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
	Subsystem: NVIDIA Corporation Device [10de:12a2]
	Kernel driver in use: vfio-pci
	Kernel modules: nouveau
```

>. From Bastion
```
[root@okd-bastion01 gpu]# oc get node worker01.eluon.okd.com  -o json | jq '.status.allocatable'
{
  "cpu": "55500m",
  "devices.kubevirt.io/kvm": "110",
  "devices.kubevirt.io/tun": "110",
  "devices.kubevirt.io/vhost-net": "110",
  "ephemeral-storage": "1078621800299",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "memory": "130572740Ki",
  "nvidia.com/gpu": "0", 
  "pods": "250"
}

[root@okd-bastion01 gpu]# oc -n kubevirt-hyperconverged edit hyperconverged
...
spec:
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  featureGates:
    sriovLiveMigration: false
    withHostPassthroughCPU: false
  infra: {}
  liveMigrationConfig:
    bandwidthPerMigration: 64Mi
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  permittedHostDevices:
    pciHostDevices:
    - externalResourceProvider: true
      pciVendorSelector: 10DE:1EB8
      resourceName: nvidia.com/TU104GL_Tesla_T4
  version: 1.4.0
  workloads: {}
...

[image:BA1DC065-D9F7-4B15-B3DB-CC3CC4601DB0-1072-0000010CA329E3C4/895A04EF-C671-4FF4-BE12-EF70B49E9786.png]

**Comment by rupang790** [comment]
I found the reason. It was about SELinux Mode. 
After I change SELinux to permissive mode on worker node, it recognized.
