### ISSUE TITLE
VM Failed Scheduling for A100 GPU

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [NVIDIA/kubevirt-gpu-device-plugin#20]
Hi,
I am trying to run VM with access to Nvidia's A100 GPU. But the VM fails to schedule as it is not able to find the GPU. 
I had set up kubevirt and and nvidia's kubevirt-gpu-plugin but I see below output:
 
**[root@node003 ~]# kubectl get pods**
NAME                          READY   STATUS    RESTARTS   AGE
virt-launcher-vmi-gpu-sgwp6   0/2     Pending   0          7s

**[root@node003 ~]# kubectl describe pod virt-launcher-vmi-gpu-sgwp6**
Name:           virt-launcher-vmi-gpu-sgwp6
...............................................................................
...............................................................................
Events:
  Warning  **FailedScheduling  4s (x3 over 87s)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/GA100_A100_SXM4_40GB.**

If I describe the node I see that the device count is 0:
Allocatable:
  cpu:                              96
  devices.kubevirt.io/kvm:          110
  devices.kubevirt.io/tun:          110
  devices.kubevirt.io/vhost-net:    110
  **nvidia.com/GA100_A100_SXM4_40GB:  0**
  pods:                             110

Thanks,
Vaibhav

**Comment by rthallisey** [comment]
What do you see when you run `lspci -nnk -d 10de:`?  Here's an example output from an A100 GPU:
```bash
# lspci -nnk -d 10de:
41:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:2235] (rev a1)
        Subsystem: NVIDIA Corporation Device [10de:145a]
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_vgpu_vfio, nvidi
```
This would make it so the pgpu on the Node appears as `nvidia.com/2235`.

On a related note, if you are using sriov for vgpus with this card, be aware that the plugin does not currently support it.  It's being worked on.

**Comment by vaibhavraizada-hcl** [comment]
Hi Ryan
Below is the output of the command:
`
$ lspci -nnk -d 10de:
01:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:20b0] (rev a1)
        Subsystem: NVIDIA Corporation Device [10de:144e]
        Kernel driver in use: vfio-pci
        Kernel modules: nouveau, nvidia_drm, nvidia
`
However, as noted above in my issue, the A100 still does not appear in the output of command 'kubectl describe node'.

One more thing to note is that I also have a Tesla T4 on the node and it appears as `nvidia.com/TU104GL_Tesla_T4: 1`

Thanks,
Vaibhav

**Comment by vaibhavraizada-hcl** [comment]
Hi Ryan,

My node shows following as `allocatable` :

`
Allocatable:
`
`
cpu: 96
`
`
devices.kubevirt.io/kvm: 110
`
`
devices.kubevirt.io/tun: 110
`
`
devices.kubevirt.io/vhost-net: 110
`
`
nvidia.com/GA100_A100_SXM4_40GB: 0
`
`
pods: 110
`

Thanks,
Vaibhav

**Comment by rthallisey** [comment]
OK, the device plugin sees the A100 GPU as `nvidia.com/GA100_A100_SXM4_40GB`, so have a look in the logs to see why `0` are `Allocatable`.

**Comment by rthallisey** [comment]
@ vaibhavraizada-hcl can you post the logs from the Device Plugin?
