### ISSUE TITLE
VMI Failed for GPU A40: Could not open '/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso': Invalid argument'

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [NVIDIA/kubevirt-gpu-device-plugin#24]
Tried to create a VM Instance but it failed. This VM instance needs access to Nvidia GPU Card A40. Output of command kubectl describe vmi vmi-gpu is below:

`LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2021-07-27T04:19:23.102128Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}: file system may not support O_DIRECT\n2021-07-27T04:19:23.102198Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}: Could not open '/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso': Invalid argument')"`

Below is the output of command `kubectl describe node node-name` :

Allocatable:
  cpu:                            96
  devices.kubevirt.io/kvm:        110
  devices.kubevirt.io/tun:        110
  devices.kubevirt.io/vhost-net:  110
  ephemeral-storage:              86973087600
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         1056605844Ki
  nvidia.com/2235:                2
  nvidia.com/TU104GL_Tesla_T4:    2
  pods:                           110

Given below is VMI specification:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-gpu
  name: vmi-gpu
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      gpus:
      - deviceName: nvidia.com/2235
        name: gpu1
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: ovaleanu/centos:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        ssh_pwauth: True
        password: centos
        chpasswd: { expire: False }
    name: cloudinitdisk

**Comment by rthallisey** [comment]
@vaibhavraizada-hcl are you sure this isn't an issue with kubevirt or a configuration setting?  Can you check the domain from inside the virt-launcher pod and look for the device: `$ virsh dump-xml 1`?

**Comment by vaibhavraizada-hcl** [comment]
This is no more replicable, hence closing issue.
