### ISSUE TITLE
Error launching VMI: the number of GPU/s do not match the number of devices

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [NVIDIA/kubevirt-gpu-device-plugin#26]
Hi,

I am facing below error when launching a VMI. 

server error. command SyncVMI failed: "failed to creade GPU host-devices: the number of GPU/s do not match the number of devices:\nGPU: [{gpu1 nvidia.com/20b0}]\nDevice: []"

I see above error when I do "kubectl describe vmi vmi_name"

I am running a centos node with kubevirt v0.45.0 and nvidia's kubevirt-gpu-device plugin.

If i do "kubectl describe node my_node" then I do see one GPU listed as Allocatable resources.

Please let me know what is the issue here and how I can fix it.

Thanks,
Vaibhav

**Comment by salanki** [comment]
We are observing the same in 0.45

**Comment by rthallisey** [comment]
It appears to me like a regression in kubevirt, so I created https://github.com/kubevirt/kubevirt/issues/6459.  For now, I'll close this issue but we can reopen depending on the result of https://github.com/kubevirt/kubevirt/issues/6459.
