### ISSUE TITLE
which some Nvidia Model is this driver support?

### ISSUE THREAD

**Issue by redhat-demo** [NVIDIA/kubevirt-gpu-device-plugin#34]
hello

I want to consult about which some Nvidia Model is this driver support?  Have any support matrix? 

Does these model support can work with kubevirt-gpu-device-plugin?
NVIDIA GRID K2
NVIDIA GRID K1
NVIDIA TESLA M60
NVIDIA TESLA M10

**Comment by rthallisey** [comment]
The support matrix comes from https://pci-ids.ucw.cz/.  In this repo that list is held [here](https://github.com/NVIDIA/kubevirt-gpu-device-plugin/blob/master/utils/pci.ids).

You can see GRID and TESLA devices in the list so it's supported.

**Comment by redhat-demo** [comment]
thanks for your kindly reply
