### ISSUE TITLE
Manifest Uses A Container Label That Does Not Exist

### ISSUE THREAD

**Issue by MCDELTAT** [NVIDIA/kubevirt-gpu-device-plugin#35]
The example manifest at `manifests/nvidia-kubevirt-gpu-device-plugin.yaml` uses the `nvcr.io/nvidia/kubevirt-gpu-device-plugin:v1.1.0` image, which does not exist. The versions can be viewed [here][1].

Trivial PR incoming to bump that number to match what is available.

In the future, your team should probably just set up a CI pipeline that updates this value when a new label is created on master.

[1]: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/kubevirt-gpu-device-plugin/tags

**Comment by rthallisey** [comment]
Fixed in https://github.com/NVIDIA/kubevirt-gpu-device-plugin/pull/38
