### ISSUE TITLE
vGPU issue, pod crash loop: Failed to initialize NVML

### ISSUE THREAD

**Issue by danisla** [NVIDIA/kubevirt-gpu-device-plugin#5]
The DaemonSet pod enters a crashloop after detecting the vGPU devices:

```
2019/11/28 16:07:11 vGPU Map  map[P100-1B4:[{20266819-7fb2-4cc1-8ef2-8d08cee44200} {229bd41e-f049-4638-afdc-1dcaf12a72c3} {2fbb26d0-b2e4-4284-aa4b-696a4a92e944} {7aab24de-4917-43bd-abb8-e98ace3f0266}]]
2019/11/28 16:07:11 GPU vGPU Map  map[0000:00:04.0:[20266819-7fb2-4cc1-8ef2-8d08cee44200 229bd41e-f049-4638-afdc-1dcaf12a72c3 2fbb26d0-b2e4-4284-aa4b-696a4a92e944 7aab24de-4917-43bd-abb8-e98ace3f0266]]
2019/11/28 16:07:11 DP Name P100-1B4
2019/11/28 16:07:11 Devicename P100-1B4
2019/11/28 16:07:11 P100-1B4 Device plugin server ready
2019/11/28 16:07:11 In health check
2019/11/28 16:07:11 Loading NVML
2019/11/28 16:07:11 Failed to initialize NVML: could not load NVML library.
nvidia-kubevirt-gpu-device-plugin: symbol lookup error: nvidia-kubevirt-gpu-device-plugin: undefined symbol: nvmlDeviceGetCount_v2
```
----
- Platform: GCE with nested virtualization
- OS: CentOS 8, kernel 4.18.0-80.11.2.el8_0.x86_64
- GPU: P100-vws
- vGPU Manager: NVIDIA-Linux-x86_64-418.66-vgpu-kvm.run
- Kubernetes: K3s version v1.16.3-k3s.2
- KubeVirt: v0.23.0

**Comment by watermelon-brother** [comment]
I meet the same issure, do you have solve it?

**Comment by lixuehui08** [comment]
nvidia's vgpu function in kubevirt does not need license?

**Comment by shiriul** [comment]
I have same issue. Can I know what is the problem?

**Comment by sseetharaman6** [comment]
Thanks for reporting this issue. A fix will be rolled out soon.

**Comment by brunnels** [comment]
I'm seeing this issue now.  When will the fix be rolled out?  Is there a test branch?

**Comment by brunnels** [comment]
I was able to get this working.  
You need nvidia-container-runtime installed and set as default in docker or containerd.  
You also need https://github.com/NVIDIA/k8s-device-plugin

Then you need to edit the nvidia-kubevirt-gpu-dp-daemonset and add this under spec->template->spec->containers
```
      resources:
        limits:
          nvidia.com/gpu: 1
```
and this under spec->template-spec
```
      nodeSelector:
        nvidia.com/gpu: "true"
```

**Comment by mokarage** [comment]
I had the same issue and following [this](https://kubevirt.io/user-guide/virtual_machines/host-devices/#preparation-of-pci-devices-for-passthrough) fixed it.

**Comment by rthallisey** [comment]
Try the latest v1.1.1 release and see if it's still an issue.  Closing for now
