### ISSUE TITLE
unknown field "pciHostDevices" 

### ISSUE THREAD

**Issue by mike-aungsan** [NVIDIA/kubevirt-gpu-device-plugin#54]
When I apply https://github.com/NVIDIA/kubevirt-gpu-device-plugin/blob/master/examples/kubevirt-featuregate-cm.yaml, I got the following error.

error: error validating "kubevirt-featuregate-cm.yaml": error validating data: ValidationError(KubeVirt.spec.configuration): unknown field "pciHostDevices" in io.kubevirt.v1alpha3.KubeVirt.spec.configuration; if you choose to ignore these errors, turn validation off with --validate=false

I try again with 

kubectl apply -f kubevirt-featuregate-cm.yaml --validate=false

But I do not see device in VM.

lspci -nn

00:00.0 Host bridge [0600]: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller [8086:29c0]
00:01.0 VGA compatible controller [0300]: Device [1234:1111] (rev 02)
00:02.0 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.1 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.2 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.3 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.4 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.5 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.6 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:02.7 PCI bridge [0604]: Red Hat, Inc. QEMU PCIe Root port [1b36:000c]
00:1f.0 ISA bridge [0601]: Intel Corporation 82801IB (ICH9) LPC Interface Controller [8086:2918] (rev 02)
00:1f.2 SATA controller [0106]: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] [8086:2922] (rev 02)
00:1f.3 SMBus [0c05]: Intel Corporation 82801I (ICH9 Family) SMBus Controller [8086:2930] (rev 02)
01:00.0 Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1af4:1041] (rev 01)
02:00.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio SCSI [1af4:1048] (rev 01)
03:00.0 Communication controller [0780]: Red Hat, Inc. Virtio console [1af4:1043] (rev 01)
04:00.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio block device [1af4:1042] (rev 01)
05:00.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio block device [1af4:1042] (rev 01)
06:00.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio block device [1af4:1042] (rev 01)
07:00.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon [1af4:1045] (rev 01)

KUBEVRT_VERSION="v0.56.0"

**Comment by rthallisey** [comment]
@mike-aungsan https://github.com/NVIDIA/kubevirt-gpu-device-plugin/pull/58 should fix.  Thanks for opening an issue
