### ISSUE TITLE
Cannot run daemonset

### ISSUE THREAD

**Issue by SyngoPredevelopment** [NVIDIA/kubevirt-gpu-device-plugin#63]
Running the executable build on the node gets the output:
sudo ./nvidia-kubevirt-gpu-device-plugin
2023/02/20 15:50:18 Not a device, continuing
2023/02/20 15:50:18 Nvidia device  0000:23:00.0
2023/02/20 15:50:18 Iommu Group 22
2023/02/20 15:50:18 Device Id 1eb0
2023/02/20 15:50:18 Nvidia device  0000:23:00.1
2023/02/20 15:50:18 Nvidia device  0000:23:00.2
2023/02/20 15:50:18 Nvidia device  0000:23:00.3
2023/02/20 15:50:18 Error accessing file path "/sys/bus/mdev/devices": lstat /sys/bus/mdev/devices: no such file or directory
2023/02/20 15:50:18 Iommu Map map[22:[{0000:23:00.0}]]
2023/02/20 15:50:18 Device Map map[1eb0:[22]]
2023/02/20 15:50:18 vGPU Map  map[]
2023/02/20 15:50:18 GPU vGPU Map  map[]
2023/02/20 15:50:18 DP Name TU104GL_QUADRO_RTX_5000
2023/02/20 15:50:18 Devicename TU104GL_QUADRO_RTX_5000
2023/02/20 15:50:18 TU104GL_QUADRO_RTX_5000 Device plugin server ready
2023/02/20 15:50:18 healthCheck(TU104GL_QUADRO_RTX_5000): invoked

Looks like the Quadro RTX 5000 is discovered made available through ernel driver in use: vfio-pci.

But when deploying latest 
https://github.com/NVIDIA/kubevirt-gpu-device-plugin/blob/master/manifests/nvidia-kubevirt-gpu-device-plugin.yaml 
on the cluster and also having the daemonset running on that node:
nvidia-kubevirt-gpu-dp-daemonset-s27ng   0/1     CreateContainerError   0               7m19s

kubectl describe .... 
Normal   Scheduled  7m48s                 default-scheduler  Successfully assigned kube-system/nvidia-kubevirt-gpu-dp-daemonset-s27ng to predevnode6
  Warning  Failed     107s (x3 over 5m48s)  kubelet            Error: context deadline exceeded
  Normal   Pulled     106s (x4 over 7m48s)  kubelet            Container image "nvcr.io/nvidia/kubevirt-gpu-device-plugin:v1.2.0" already present on machine

Looked on the kubelet logs, nothing to be seen which is problematic. 

Any idea why the daemonset is not working ?

Having K8s v1.24.1 and cri-o://1.23.5.

**Comment by rthallisey** [comment]
This looks like an issue with the node or at the CRI/CNI/CSI layer.  Were you able to schedule other pods on this node?  Did Kubelet eventually describe what the problem was?

Feel free to post logs here and I can provide suggestions, but I'm going to close since I don't think this has to do with the device plugin.
