### ISSUE TITLE
Recommendations for configuring vfio driver

### ISSUE THREAD

**Issue by Itswag** [NVIDIA/kubevirt-gpu-device-plugin#66]
When I use the default command `grub2-mkconfig -o /boot/grub2/grub.cfg`，the vfio driver does not take effect.
```
[root@master-3 ~]# dmesg|grep -i vfio
[    7.567947] vfio-pci: probe of 0000:01:00.0 failed with error -22
……
```
Because when the system is booted for Legacy BIOS, it uses`/boot/grub2/grub.cfg`, but when my system is booted for UEFI, I should use `grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg`. This issue has been bothering me for a while. I hope can prompt in Readme.md

**Comment by rthallisey** [comment]
@Itswag can you open a pull request against the README?  I would be happy to review.
