### ISSUE TITLE
Device plugin - expose only 1 gpu for vm

### ISSUE THREAD

**Issue by talcoh2x** [NVIDIA/kubevirt-gpu-device-plugin#9]
Hi I'm wondering if I need to use with the nvidia GPU plugin that I'm using today(for containers)together with this plugin to achieve VM that has only one gpu ??? even if the KVM has 4 for example

**Comment by talcoh2x** [comment]
UP @vinaydes

**Comment by vinaydes** [comment]
Am I correctly tagged in this issue?

**Comment by sseetharaman6** [comment]
@talcoh2x , I am not sure I understand your question. Can you please elaborate a bit more on your use-case ? 
This device plugin is to allocate GPUs to Kubevirt VMs - so if that is your use case, then this is the right DP to use.  It is different from https://github.com/NVIDIA/k8s-device-plugin, which has `nvidia-docker` dependency and is specifically for container workloads.  They are mutually exclusive.

**Comment by caohuilong** [comment]
@sseetharaman6 I have the same question, Can i use [kubevirt-gpu-device-plugin](https://github.com/NVIDIA/kubevirt-gpu-device-plugin) to allocate GPUs to Kubevirt VMs and use [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) to allocate GPUs to my container workloads in the same node?

**Comment by nkwangleiGIT** [comment]
@caohuilong I don't thinks it's supported, you can only run either container or KVM workload on one node, they're exclusive.
