### ISSUE TITLE
gpu driver vfio to nouveau, kebevirt cr not change

### ISSUE THREAD

**Issue by scydas** [NVIDIA/kubevirt-gpu-device-plugin#91]
change gpu driver vfio to nouveau
![image](https://github.com/NVIDIA/kubevirt-gpu-device-plugin/assets/22952515/6422ac36-847e-43d9-be59-f11fa41a24ea)

kubevirt cr 
![image](https://github.com/NVIDIA/kubevirt-gpu-device-plugin/assets/22952515/60716faf-9b6f-46b0-807c-6e294f40588c)

pciHostDevices not delete

**Comment by rthallisey** [comment]
You have to update the kubevirt cr yourself if you don't want to use this GPU.  Changing the driver will only make it un-usable to the admin, but it will still be advertised on the Node.

Feel free to reopen if there's still an issue.
